apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-challenge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sport-enlace-sas/frontend-challenge-base.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
